### ISSUE TITLE
node-uuid missing via CLI install

### ISSUE THREAD

**Issue by pimviergever** [Inversion-NL/nl.inversion.wunderground#28]
Just tried to install version 0.30 on Homey 1.1.2. When I run the project via CLI, I get the following debug log:

1/4 - Archiving...
2/4 - Uploading to Homey @ 192.168.1.34:80...
3/4 - Running `nl.inversion.wunderground`, press CTRL+C to abort...
4/4 - Debugging...

-------------------------------------------------
[homey-log] App is running in debug mode, disabling log
Initializing Weather Underground

checkInsightsLogs
Registering trigger and condition listeners
Registering settings listener
Registering app unload listener

Check settings
No unit value existed, resetting to auto
Use error notifications: true
Error: Cannot find module 'node-uuid'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at generateUniqueId (/app.js:1463:16)
    at Object.self.checkSettings (/app.js:192:28)
    at Object.self.init (/app.js:75:14)
    at /bootstrap.js:222:19
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**Comment by Inversion-NL** [comment]
Code on GitHub isn't complete at this moment

**Comment by Inversion-NL** [comment]
Just updated the code (with node-uuid module ;-) )

**Comment by pimviergever** [comment]
Just ran the project with athom-cli: no errors
After that installed the project (0.30) via cli on Homey 1.1.2: no errors

Fetching temperatures happened without errors. So far so good!

**Comment by Inversion-NL** [comment]
Great, let me know how it works
