### ISSUE TITLE
Temperature isn't a number?

### ISSUE THREAD

**Issue by DieterKoblenz** [Inversion-NL/nl.inversion.wunderground#8]
When I use the action card "Temperature has changed" the attached tag temperature can't be used to set for example a better logic number var or to input as outside temperature in the opentherm gateway app. Temperature is set as a String, that is unwanted behaviour (at least for me).

**Comment by Inversion-NL** [comment]
Good catch!
I'll look into it. Though I'm a bit short on time because we are expecting a baby in the next 3 weeks and we'll have to arrange a lot of small things :)

**Comment by Inversion-NL** [comment]
Tried this but I'm unable to get the token into the better logic card?
Am I doing something wrong or is the problem your having?

**Comment by DieterKoblenz** [comment]
I am unable to get the token into a numeric better logic card or (more importantly) in the temperature card of the opentherm gateway.

**Comment by Inversion-NL** [comment]
That's an issue of Homey or Better Logic.
I can't get any card into Better Logic card
