### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by ruudmens** [Inversion-NL/nl.inversion.wunderground#9]
I keep getting the following error after updating Homey to 0.8.39:

> Stack trace:
> 
> TypeError: Cannot read property 'relative_humidity' of undefined
> at null.<anonymous> (/app.js:529:55)
> at Request._callback (/node_modules/wundergroundnode/lib/wundergroundnode.js:137:26)
> at Request.self.callback (/node_modules/request/request.js:199:22)
> at emitTwo (events.js:87:13)
> at Request.emit (events.js:172:7)
> at Request.<anonymous> (/node_modules/request/request.js:1036:10)
> at emitOne (events.js:82:20)
> at Request.emit (events.js:169:7)
> at IncomingMessage.<anonymous> (/node_modules/request/request.js:963:12)
> at emitNone (events.js:72:20)

**Comment by Inversion-NL** [comment]
Yes, I'm submitting a new version for approval today

**Comment by Inversion-NL** [comment]
Solved since 0.2.0
